### ISSUE TITLE
recoverWith throws error in multicast (since 1.1.2)

### ISSUE THREAD

**Issue by maxhoffmann** [mostjs/multicast#14]
`@most/multicast` version `1.1.2` and `1.1.3` currently break our app. I map over a stream and try to access a property of an object. If this fails `recoverWith` a default value.

Since `1.1.2` this does not work anymore and `@most/multicast` throws an error at this line, where `this.sink` is undefined:

![screen shot 2016-05-10 at 14 55 04](https://cloud.githubusercontent.com/assets/1227441/15148881/5352a722-16bf-11e6-9cf7-854c3aa82f9f.png)

I’ll downgrade for now. Hope this is enough information.

**Comment by maxhoffmann** [comment]
I’ve tried installing from `master`, but this doesn’t solve the issue (https://github.com/mostjs/multicast/commit/bc817042ea60ca0e782649d6f2346f0b6c7527bf).

**Comment by briancavalier** [comment]
Thanks @maxhoffmann.  Sorry for the issue.  Did downgrading to 1.1.1 fix the issue?

**Comment by briancavalier** [comment]
I'm trying to reproduce this based on the description, and I'm having trouble.  Do you have a test case that I could use?  I tried variations of things like:

```
const s = from([1, 2, 3])
  .map(x => x.foo.bar)
  .recoverWith(e => just('worked'))

const sm = multicast(s)

sm.observe(x => console.log(x)).catch(e => console.error(e.stack))
sm.drain().catch(e => console.error(e.stack))
sm.drain().catch(e => console.error(e.stack))
```

With and without the additional observers (`sm.drain()...`) and moving the multicast around: instead of multicasting `s`, multicasting only `from([1, 2, 3])` or only `from([1, 2, 3]).map(...)`.  It all worked as I expected, so I'm probably not tickling it in the right way!

Also, you may want to try the upcoming version in https://github.com/mostjs/multicast/pull/15.  It gets rid of the (scary, I have to admit!) internal mutable state shuffling that's going on in 1.1.2 and 1.1.3 for a much nicer immutable data structure.

**Comment by briancavalier** [comment]
I managed to reproduce it, and I found the version in #15 does indeed fix it.  I stumbled upon some code in another issue that reproduced it:

``` js
most.create((add, end, err) => {
    add('dummy element');
    end();
})
    .map(e => {
        throw new Error('This should be reported');
    })
    .drain()
    .catch(err => console.error(err.message));
```

So, I'll work on getting #15 merged soon.

**Comment by maxhoffmann** [comment]
Hey Brian! Sorry for the late response. Downgrading `1.1.1` fixed the issue. I’ve just tried `1.1.4` and it does fix it, too. Thanks! :)

**Comment by briancavalier** [comment]
Cool, thanks for confirming, @maxhoffmann.
